
name: Mirror Repository

on:
  push:
    branches:
      - '**'

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to mirror
        run: |
          git remote add mirror https://x-access-token:${{ secrets.MirrorCheck }}@github.com/jeetendravasisht/Grocery-store.git
          git push mirror --mirror
