name: Mirror Repository

on:
  push:
    branches:
      - master

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Configure mirror
        run: |
          git remote add mirror https://x-access-token:${{ secrets.MIRRORCHECK }}@github.com/jeetendravasisht/Grocery-store.git

      - name: Check mirror access
        run: |
          git ls-remote mirror

      - name: Push to mirror
        run: |
          git push mirror --mirror
